// <auto-generated />
using CarTicketBookingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarTicketBookingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919185757_SeedTravelRoutes")]
    partial class SeedTravelRoutes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarTicketBookingSystem.Models.TravelRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TravelTime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TravelRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fare = 800m,
                            From = "Dhaka",
                            To = "Chattogram",
                            TravelTime = "8h"
                        },
                        new
                        {
                            Id = 2,
                            Fare = 700m,
                            From = "Dhaka",
                            To = "Sylhet",
                            TravelTime = "6h"
                        },
                        new
                        {
                            Id = 3,
                            Fare = 600m,
                            From = "Dhaka",
                            To = "Rajshahi",
                            TravelTime = "7h"
                        },
                        new
                        {
                            Id = 4,
                            Fare = 650m,
                            From = "Dhaka",
                            To = "Khulna",
                            TravelTime = "7h"
                        },
                        new
                        {
                            Id = 5,
                            Fare = 550m,
                            From = "Dhaka",
                            To = "Barishal",
                            TravelTime = "6h"
                        },
                        new
                        {
                            Id = 6,
                            Fare = 400m,
                            From = "Chattogram",
                            To = "Cox's Bazar",
                            TravelTime = "4h"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
